name: gruendermotor
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - asttokens=2.0.5
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - branca=0.6.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - catalogue=2.0.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - comm=0.1.2
  - cryptography=39.0.1
  - cymem=2.0.6
  - cython-blis=0.7.8
  - dataclasses=0.8
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - flit-core=3.6.0
  - folium=0.14.0
  - fuzzywuzzy=0.18.0
  - geographiclib=1.52
  - geopy=2.2.0
  - giflib=5.2.1
  - glib=2.69.1  
  - importlib-metadata=4.11.3
  - importlib_resources=5.2.0
  - ipykernel=6.19.2
  - ipython=8.10.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.2
  - jupyter_core=5.2.0
  - jupyter_server=1.23.4
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.19.0
  - jupyterlab_widgets=1.0.0
  - langcodes=3.3.0
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.2
  - libiconv=1.16
  - libogg=1.3.5
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.5.0
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzlib=1.2.13
  - lxml=4.9.1
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4

  - murmurhash=1.0.7
  - nbclassic=0.5.2
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - nest-asyncio=1.5.6
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - numexpr=2.8.4
  - numpy=1.23.5
  - openpyxl=3.0.10

  - packaging=23.0
  - pandas=1.5.3
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathy=0.10.1
  - pcre=8.45
  - pickleshare=0.7.5
  - pip=23.0.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.5.2
  - ply=3.11
  - preshed=3.0.6
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pydantic=1.8.2
  - pyopenssl=23.0.0
  - pyparsing=3.0.9


  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-dotenv=0.21.0
  - python-fastjsonschema=2.16.2
  - python-levenshtein=0.12.2
  - pytz=2022.7.1
  - pyzmq=23.2.0

  - send2trash=1.8.0
  - setuptools=65.6.3
  - shellingham=1.5.0.post1
  - sip=6.6.2
  - six=1.16.0
  - smart_open=5.2.1
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.1
  - spacy-model-en_core_web_md=3.3.0
  - spacy-model-en_core_web_sm=3.3.0
  - sqlite=3.40.1
  - srsly=2.4.4
  - stack_data=0.2.0
  - tbb=2021.7.0
  - terminado=0.17.1
  - testpath=0.6.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.7.1
  - typer=0.4.1
  - typing-extensions=4.4.0
  - tzdata=2022g
  - wasabi=0.9.1
  - wcwidth=0.2.5
  - webdriver-manager=3.8.3
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - widgetsnbextension=3.5.2
  - xz=5.2.10
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.
pip:
  - absl-py==2.0.0
  - aiohttp==3.8.4
  - aiosignal==1.3.1
  - arrow==1.2.3
  - astunparse==1.6.3
  - async-timeout==4.0.2
  - automat==22.10.0
  - bertopic==0.16.2
  - blinker==1.6.2
  - blis==0.7.9
  - cachetools==5.3.0
  - caffeine==0.5
  - chardet==3.0.4
  - circlify==0.15.0
  - click==8.1.3
  - click-plugins==1.1.1
  - cligj==0.7.2
  - confection==0.0.4
  - constantly==23.10.4
  - contourpy==1.0.7
  - cssselect==1.2.0
  - cssutils==2.7.1
  - cycler==0.11.0
  - cython==0.29.37
  - datasets==2.18.0
  - dill==0.3.8
  - dm-tree==0.1.8
  - docopt==0.6.2
  - exceptiongroup==1.1.3
  - fake-useragent==0.1.14
  - filelock==3.13.1
  - fiona==1.9.3
  - flask==2.3.2
  - flatbuffers==23.5.26
  - fonttools==4.39.4
  - frozenlist==1.3.3
  - fsspec==2023.12.2
  - gast==0.4.0
  - gensim==4.3.2
  - geopandas==0.13.0
  - geos==0.2.3
  - google-api-core==2.11.0
  - google-api-python-client==2.78.0
  - google-auth==2.18.0
  - google-auth-httplib2==0.1.0
  - google-auth-oauthlib==0.4.6
  - google-pasta==0.2.0
  - googleapis-common-protos==1.59.0
  - googletrans==3.1.0a0
  - greenlet==3.0.3
  - grpcio==1.60.0
  - h11==0.9.0
  - h2==3.2.0
  - h5py==3.10.0
  - hdbscan==0.8.36
  - hpack==3.0.0
  - hstspreload==2023.1.1
  - httpcore==0.9.1
  - httplib2==0.22.0
  - httpx==0.13.3
  - huggingface-hub==0.20.2
  - hyperframe==5.2.0
  - hyperlink==21.0.0
  - idna==2.10
  - incremental==24.7.2
  - itemadapter==0.9.0
  - itemloaders==1.3.1
  - itsdangerous==2.1.2
  - jmespath==1.0.1
  - joblib==1.3.2
  - kaleido==0.2.1
  - keras==2.11.0
  - keras-preprocessing==1.1.2
  - kiwisolver==1.4.4
  - libclang==16.0.6
  - littleutils==0.2.2
  - llvmlite==0.42.0
  - markdown==3.5.2
  - markdown-it-py==3.0.0
  - matplotlib==3.7.1
  - mdurl==0.1.2
  - ml-dtypes==0.3.2
  - more-itertools==9.1.0
  - mpmath==1.3.0
  - multidict==6.0.4
  - multiprocess==0.70.16
  - munch==2.5.0
  - namex==0.0.7
  - networkx==3.2.1
  - nicknames==0.1.3
  - nltk==3.8.1
  - num2words==0.5.12
  - numba==0.59.1
  - oauthlib==3.2.2
  - opt-einsum==3.3.0
  - outcome==1.2.0
  - parsel==1.9.1
  - pillow==9.5.0
  - playwright==1.45.1
  - plotly==5.14.1
  - proj==0.2.0
  - protego==0.3.1
  - protobuf==3.19.6
  - pyairtable==1.5.0
  - pyarrow==15.0.1
  - pyarrow-hotfix==0.6
  - pyasn1==0.5.0
  - pyasn1-modules==0.3.0
  - pycountry==23.12.11
  - pydispatcher==2.0.7
  - pyee==11.1.0
  - pygments==2.17.2
  - pynndescent==0.5.12
  - pyproj==3.5.0
  - python-snovio==0.2.1
  - pyyaml==6.0.1
  - queuelib==1.7.0
  - rapidfuzz==3.9.4
  - regex==2022.10.31
  - requests==2.29.0
  - requests-file==2.1.0
  - requests-oauthlib==1.3.1
  - rfc3986==1.5.0
  - rich==13.7.1
  - rsa==4.9
  - safetensors==0.4.1
  - scikit-learn==1.4.0
  - scipy==1.11.4
  - scrapy==2.11.2
  - scrapy-playwright==0.0.40
  - search-engine-parser==0.6.8
  - selenium==4.13.0
  - sentence-transformers==3.0.1
  - service-identity==24.1.0
  - shapely==2.0.1
  - sorcery==0.2.2
  - sortedcontainers==2.4.0
  - spacy==3.4.4
  - sympy==1.12
  - tenacity==8.2.2
  - tensorboard==2.11.2
  - tensorboard-data-server==0.6.1
  - tensorboard-plugin-wit==1.8.1
  - tensorflow==2.11.0
  - tensorflow-estimator==2.11.0
  - tensorflow-intel==2.11.0
  - tensorflow-io-gcs-filesystem==0.31.0
  - termcolor==2.4.0
  - thinc==8.1.10
  - threadpoolctl==3.2.0
  - tldextract==5.1.2
  - tokenizers==0.15.0
  - torch==2.1.2
  - transformers==4.36.2
  - trio==0.22.2
  - trio-websocket==0.11.1
  - twisted==24.3.0
  - twisted-iocpsupport==1.0.4
  - umap-learn==0.5.6
  - uritemplate==4.1.1
  - urllib3==1.26.18
  - w3lib==2.2.1
  - waybackpy==3.0.6
  - werkzeug==2.3.4
  - wordcloud==1.9.3
  - wrapt==1.14.1
  - wsproto==1.2.0
  - xxhash==3.4.1
  - yarl==1.9.2
  - zope-interface==7.0.1
